services:
  - type: web
    name: django-app
    env: python
    plan: free
    branch: deploy
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: haldiram-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.13.0
databases:
  - name: haldiram-db

