# Generated by Django 5.2.7 on 2025-11-14 07:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_suggestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'pgadmin_extra_suggestion',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraph',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'pgadmin_knowledgegraph',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'pgadmin_metrics',
            },
        ),
        migrations.CreateModel(
            name='RCA',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'pgadmin_rca',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('tables', models.JSONField(blank=True, default=list)),
                ('knowledge_graph_data', models.JSONField(blank=True, default=dict)),
                ('rca_list', models.JSONField(blank=True, default=list)),
                ('pos_tagging', models.JSONField(blank=True, default=list)),
                ('metrics_data', models.JSONField(blank=True, default=dict)),
                ('extra_suggestions', models.TextField(blank=True, default='')),
                ('kg_auto_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pgadmin_module',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_name', '-created_at'], name='pgadmin_mod_user_na_819251_idx')],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(default='New Chat', max_length=255)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='pgadmin.module')),
            ],
            options={
                'db_table': 'pgadmin_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_user', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pgadmin.conversation')),
            ],
            options={
                'db_table': 'pgadmin_message',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['conversation', 'timestamp'], name='pgadmin_mes_convers_fa84bb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['session_id', '-updated_at'], name='pgadmin_con_session_6b8450_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['module', '-updated_at'], name='pgadmin_con_module__4f09da_idx'),
        ),
    ]
