# Generated by Django 5.2.7 on 2025-10-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('tables', models.JSONField()),
                ('knowledge_graph', models.FileField(blank=True, null=True, upload_to='knowledge_graphs/')),
                ('metrics', models.FileField(blank=True, null=True, upload_to='metrics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
