# Generated by Django 5.2.7 on 2025-11-13 07:29

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(default='New Chat', max_length=255)),
                ('entities', models.JSONField(blank=True, default=dict, null=True)),
                ('context', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pgadmin_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Extra_suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'pgadmin_extra_suggestion',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'pgadmin_knowledgegraph',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'pgadmin_metrics',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('tables', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('knowledge_graph_data', models.JSONField(blank=True, default=dict, null=True)),
                ('metrics_data', models.JSONField(blank=True, default=dict, null=True)),
                ('rca_list', models.JSONField(blank=True, default=list, null=True)),
                ('pos_tagging', models.JSONField(blank=True, default=list, null=True)),
                ('extra_suggestions', models.TextField(blank=True, null=True)),
                ('kg_auto_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pgadmin_module',
            },
        ),
        migrations.CreateModel(
            name='RCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'pgadmin_rca',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_user', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pgadmin.conversation')),
            ],
            options={
                'db_table': 'pgadmin_message',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='pgadmin.module'),
        ),
    ]
