# Generated by Django 5.2.7 on 2025-11-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='relationships',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
