# Generated by Django 5.2.7 on 2025-12-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0002_module_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='selected_columns',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
