# Generated by Django 5.2.7 on 2025-10-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0002_knowledgegraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgegraph',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
