# Generated by Django 5.2.7 on 2025-10-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0003_alter_knowledgegraph_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgegraph',
            name='column_name',
        ),
        migrations.RemoveField(
            model_name='knowledgegraph',
            name='desc',
        ),
        migrations.AddField(
            model_name='knowledgegraph',
            name='columns_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgegraph',
            name='table_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
