# Generated by Django 5.2.7 on 2025-10-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0004_remove_knowledgegraph_column_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgegraph',
            name='columns_info',
        ),
        migrations.RemoveField(
            model_name='knowledgegraph',
            name='table_name',
        ),
        migrations.AddField(
            model_name='knowledgegraph',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
