# Generated by Django 5.2.7 on 2025-10-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0006_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
