# Generated by Django 5.2.7 on 2025-11-10 13:01

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgadmin', '0009_conversation_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='session',
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='pgadmin_con_session_6b8450_idx',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='module',
            name='knowledge_graph',
        ),
        migrations.RemoveField(
            model_name='module',
            name='metrics',
        ),
        migrations.AddField(
            model_name='conversation',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='pgadmin.module'),
        ),
        migrations.AddField(
            model_name='extra_suggestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='extra_suggestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgegraph',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgegraph',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='metrics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='extra_suggestions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='module',
            name='kg_auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='knowledge_graph_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='module',
            name='metrics_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='module',
            name='pos_tagging',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='module',
            name='rca_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rca',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rca',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='New Chat', max_length=200),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='module',
            name='tables',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='module',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
